# Generated by Django 5.1.7 on 2025-05-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(help_text='Upload your AssetBundle (.bundle) for this model', upload_to='models/')),
                ('latitude', models.FloatField(help_text='GPS latitude (decimal degrees)')),
                ('longitude', models.FloatField(help_text='GPS longitude (decimal degrees)')),
                ('altitude', models.FloatField(blank=True, help_text='Optional altitude (meters)', null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.construction')),
            ],
        ),
    ]
