# Generated by Django 5.1.7 on 2025-05-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_model3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(help_text='Upload your AssetBundle (.bundle) for this model', upload_to='bundles/'),
        ),
    ]
