# Generated by Django 5.1.9 on 2025-06-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_model3d_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtticSkeleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='attic_skeleton/')),
            ],
        ),
    ]
